solace:
  connection:
    brokerHost: tcps://mr-connection-pibs5pcubhg.messaging.solace.cloud:55443
    messageVpn: scaler-demo
    clientUsername: solace-cloud-client
    clientPassword: ^wKy9XzruC7JauCg
  eventPortal:
    apiToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1hYXNfcHJvZF8yMDIwMDMyNiIsInR5cCI6IkpXVCJ9.eyJvcmciOiJzb2xhY2VjdG8iLCJvcmdUeXBlIjoiRU5URVJQUklTRSIsInN1YiI6ImhrNDA2NnpnMHY1IiwicGVybWlzc2lvbnMiOiJBQUFBQUlBRUFBQUFXd0FBWUFBQUFBQUFBQUFBQUFBQUFJQXhDb01BSUFDZ0x2Ly9nNVZmQlo0QVdFTUQ0NFkvTVFNUkVBPT0iLCJhcGlUb2tlbklkIjoicjVsYTJ5cWo1MnEiLCJpc3MiOiJTb2xhY2UgQ29ycG9yYXRpb24iLCJpYXQiOjE3MDY4MjQ0NDR9.mqkFQF4VoOjmgpyT7fmNM40xFp6_iWZgPe69Wi-qKEGu8tDRLXmaP638gWbrZhPwoF8U1d6bIrmnEBGIwcH2kn7CW2qsriWK2WueBlzFMNc7ypuX557UqxYK2IqXDu2v_QYrpYmp_orsaXSg6d6xNYm_4MY-j83htpVgUX4naCtYB2lMMT0Iu70UMdhxRqphP4Wkwdwwjn-wvKbnaBXZ-iOMNOaBbBcXlXIlqI1fTLPCej9kCoM-IAYgOG59bCEk9Wb_J_UDr2DRaUYpFxyB9ERBx0itk5iI2MupQSJzjtcz_kgA4ZxE1SoFnq3ZVgaRzm-OisBoPdbUqJkBawadaw
